#pragma once

#define SAFE_DELETE(p) {if(p) { delete(p); p = NULL;} } 

#define BACKGROUND_COLOR D3DCOLOR_XRGB(0, 0, 0)
#define DIRECTINPUT_VERSION 0x0800

#define KEYBOARD_BUFFER_SIZE 1024	
#define WINDOW_CLASS_NAME	L"Castle Vania"
#define FULLSCREEN	false
#define MAIN_WINDOW_TITLE	L"Castle Vania"
#define SCREEN_WIDTH	640
#define SCREEN_HEIGHT	480

#define FPS					200

#define GAME_FONT			L"Resource\\font\\prstart.ttf"
#define MAX_TIME_PER_FRAME		(DWORD)1000 / FPS


#define ID_TEX_BBOX -100	


#define	ID_TEX_LEVEL_ONE		1
#define	ID_TEX_LEVEL_TWO		2

#define ID_TEX_SIMON 101
#define ID_TEX_WHIP 201
#define ID_TEX_EFFECT 301
#define ID_TEX_CANDLE 401
#define ID_TEX_GROUND 501

#define ID_TEX_ITEMS 601
#define ID_TEX_KNIFE 701




#define GRAVITY						0.002f



#define SIMON_WALKING_SPEED			0.13f 
#define SIMON_JUMP_SPEED_Y			0.5f
#define SIMON_JUMP_DEFLECT_SPEED	0.2f
#define SIMON_DIE_DEFLECT_SPEED		0.5f
#define ITEM_FALLING_SPEED			0.1f
#define WATER_SPLASSING_SPEED		0.1f
#define ITEM_Knife_SPEED			0.5f 
#define WEAPON_KNIFE_SPEED			0.3f

#define WEAPON_KNIFE	0

#define GROUND_WIDTH				32
#define GROUND_HEIGHT				32

#define LCANDLE_WIDTH				32
#define LCANDLE_HEIGHT				64

#define MCANDLE_WIDTH				16
#define MCANDLE_HEIGHT				32

#define SIMON_BBOX_WIDTH			40
#define SIMON_BBOX_HEIGHT			60

#define WHIP_BBOX_HEIGHT			20
#define WHIP_BBOX_WIDTH				40

#define BIG_HEART_BBOX_WIDTH		24
#define	BIG_HEART_BBOX_HEIGHT		20
#define SMALL_HEART_BBOX_WIDTH		16
#define	SMALL_HEART_BBOX_HEIGHT		16

#define MORNING_STAR_BBOX_WIDTH		32
#define MORNING_STAR_BBOX_HEIGHT	32

#define WEAPON_KNIFE_BBOX_WIDTH	        32
#define WEAPON_KNIFE_BBOX_HEIGHT		18


#define SIMON_DIE			10
#define SIMON_STAND_IDLE	0
#define SIMON_WALK			1
#define SIMON_SIT			2
#define SIMON_JUMP			3
#define SIMON_SIT_ATTACK	4
#define SIMON_STAND_ATTACK	5
#define SIMON_EFFECT		6

#define SIMON_ANI_IDLE_UP_STAIR_RIGHT	19
#define SIMON_ANI_IDLE_DOWN_STAIR_RIGHT	20
#define SIMON_ANI_IDLE_UP_STAIR_LEFT	21
#define SIMON_ANI_IDLE_DOWN_STAIR_LEFT	22

#define SIMON_ANI_ATK_UP_STAIR_RIGHT	23
#define SIMON_ANI_ATK_DOWN_STAIR_RIGHT	24
#define SIMON_ANI_ATK_UP_STAIR_LEFT		25
#define SIMON_ANI_ATK_DOWN_STAIR_LEFT	26

#define SIMON_ANI_HURT_RIGHT			27
#define SIMON_ANI_HURT_LEFT				28	
#define SIMON_ANI_DIE_RIGHT				29
#define SIMON_ANI_DIE_LEFT				30

#define WHIP_ANI_NORMAL_RIGHT			0
#define WHIP_ANI_LV1_RIGHT				1
#define WHIP_ANI_LV2_RIGHT				2
#define WHIP_ANI_NORMAL_LEFT			3
#define WHIP_ANI_LV1_LEFT				4
#define WHIP_ANI_LV2_LEFT				5



#define ITEM_SMALL_HEART		 	0
#define ITEM_BIG_HEART		 		1
#define ITEM_WHIP					2
#define ITEM_KNIFE					3


#define SIMON_EFFECT_TIME			450
#define SIMON_ATTACK_TIME			350
#define SIMON_UNTOUCHABLE_TIME		2500
#define ITEM_TIME_DESTROYED         5000
#define EFFECTDEAD_TIME				600
#define WHIP_NORMAL 0
#define WHIP_SHORT	1
#define WHIP_LONG	2

#define STAGE1	1
#define STAGE2	2

#define ANI_BIG_CANDLE		0
#define ANI_SMALL_CANDLE	1

#define ANI_GROUND_LV1		0
#define ANI_GROUND_LV2		1

#define EFFECTDEAD_STAR		0
#define EFFECTDEAD_FIRE		1

#define MAP_WIDTH_LV1	(int)1536
#define MAP_HEIGHT_LV1	(int)384